flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- multiset-0.3.3
- parsec-3.1.11
- text-1.2.2.1
- union-find-array-0.1.0.2
resolver: ghc-8
